# Generated by Django 3.1.2 on 2020-10-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mywebsitedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
            ],
        ),
    ]
